### ISSUE TITLE
1.2.3.1 Instances and Equality - Written Educational Material

### ISSUE THREAD

**Issue by MZsizsa** [kode-konveyor/education#31]
Based on the video (https://youtu.be/i40mYbIt3Hg), you can also find it in the moodle with the same title as the title of this issue.
You are required to write an educational material, according to our standard.
 
Standard for the education: https://kodekonveyor.com/educationstandard
The price for this task is 15 Euro.

**Comment by Tanwar-1** [comment]
grab
