### ISSUE TITLE
Instances and Equality

### ISSUE THREAD

**Issue by Tanwar-1** [kode-konveyor/education#32]
Instances and Equality

**Comment by Tanwar-1** [comment]
Content is ready

**Comment by magwas** [comment]
relates to #31

**Comment by Tanwar-1** [comment]
grab

**Comment by Tanwar-1** [comment]
https://learn.kodekonveyor.com/mod/page/view.php?id=114

**Comment by MZsizsa** [comment]
Hi Gopal, we checked the text you created. We see that you put a lot of effort into it. However, we are very sorry that it seems that we weren’t able to explain exactly what we expected.
The text you created is more or less the transcript of the video, whereas we would like to see just the new definitions and material that was in the video.

I would advice you to check the video and the lecture: 1.2.1 Variables and primitive types (https://learn.kodekonveyor.com/course/view.php?id=2#section-6) the video (https://learn.kodekonveyor.com/mod/page/view.php?id=25) and the text (https://learn.kodekonveyor.com/mod/page/view.php?id=26), and kindle ask to redo the lecture based on those.
