### ISSUE TITLE
Setting up the environment: Git Inside Eclipse

### ISSUE THREAD

**Issue by swapsonawane** [kode-konveyor/education#37]
#30 Setting up the environment: Git and GitHub - Written Educational Material

**Comment by swapsonawane** [comment]
[GithubEclipse.docx](https://github.com/kode-konveyor/education/files/4609184/GithubEclipse.docx)

**Comment by MZsizsa** [comment]
HI!
I' sorry it seems, I was not clear enough.
It is short of transcript of the video. That is not what we want.
Here you should talk about:
what is git for
version control system
why are we using it
how is helping team work
I hope it is clear!

**Comment by swapsonawane** [comment]
[Git-VCS.docx](https://github.com/kode-konveyor/education/files/4622214/Git-VCS.docx)

**Comment by MZsizsa** [comment]
Accepted

**Comment by swapsonawane** [comment]
[Git-VCS.docx](https://github.com/kode-konveyor/education/files/4763853/Git-VCS.docx)
PFA updated doc as per the last review.
